name: Repo

on:
  # Rebuild once a day
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    strategy:
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.github.hydroxycarbamide.Gradience.flatpak
          manifest-path: build-aux/flatpak/com.github.hydroxycarbamide.Gradience.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          verbose: true

      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: com.github.hydroxycarbamide.Gradience.Devel.flatpak
          manifest-path: build-aux/flatpak/com.github.hydroxycarbamide.Gradience.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.variant.arch }}
          gpg-sign: ${{ steps.gpg.outputs.fingerprint }}
          verbose: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.hydroxycarbamide.Gradience.Devel-${{ matrix.variant.arch }}
          path: com.github.hydroxycarbamide.Gradience.Devel.flatpak

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.hydroxycarbamide.Gradience-${{ matrix.variant.arch }}
          path: com.github.hydroxycarbamide.Gradience.flatpak
